#!/usr/bin/env python3
"""Generates pack/assets/hcpack/font/hud.json and CODEPOINTS.md."""
import json
import pathlib

# The two tuning knobs. Raising ASCENT moves the glyph up. ASCENT <= HEIGHT.
HEIGHT = 16
ASCENT = -28

BOSSES = [
    ("dragon_grey", 0xE000), ("dragon", 0xE001),
    ("wither_grey", 0xE002), ("wither", 0xE003),
    ("warden_grey", 0xE004), ("warden", 0xE005),
    ("elder_grey",  0xE006), ("elder",  0xE007),
]

# Space advances. U+E100+i is negative, U+E110+i is the same value positive.
WIDTHS = [1, 2, 3, 4, 8, 16, 17, 32, 64]

# Armor block: U+E200 + material*4 + slot. Contiguous through U+E223.
ARMOR_BASE = 0xE200
MATERIALS = ["netherite", "diamond", "iron", "golden",
             "chainmail", "copper", "leather", "turtle", "empty"]
SLOTS = ["helmet", "chestplate", "leggings", "boots"]
# turtle is helmet-only; its other three codepoints stay unassigned.
MISSING = {("turtle", "chestplate"), ("turtle", "leggings"), ("turtle", "boots")}

# Durability block: U+E230 + filled, filled in 0..13.
BAR_BASE = 0xE230
BAR_STEPS = 14


def armor_cp(material, slot):
    return ARMOR_BASE + MATERIALS.index(material) * 4 + SLOTS.index(slot)


def build():
    advances = {}
    for i, w in enumerate(WIDTHS):
        advances[chr(0xE100 + i)] = -w
        advances[chr(0xE110 + i)] = w

    glyphs = list(BOSSES)
    for m in MATERIALS:
        for s in SLOTS:
            if (m, s) in MISSING:
                continue
            name = f"armor_{m}_{s}"
            glyphs.append((name, armor_cp(m, s)))
    glyphs += [(f"bar_{n}", BAR_BASE + n) for n in range(BAR_STEPS)]

    providers = [{"type": "space", "advances": advances}]
    providers += [
        {"type": "bitmap", "file": f"hcpack:hud/{name}.png",
         "height": HEIGHT, "ascent": ASCENT, "chars": [chr(cp)]}
        for name, cp in glyphs
    ]

    root = pathlib.Path(__file__).parents[2]
    out = root / "pack/assets/hcpack/font/hud.json"
    out.write_text(json.dumps({"providers": providers}, indent=2, ensure_ascii=True) + "\n")
    (root / "CODEPOINTS.md").write_text(codepoints_md(glyphs, advances))
    print(f"{out}: height={HEIGHT} ascent={ASCENT}, {len(glyphs)} glyphs")
    return glyphs


def codepoints_md(glyphs, advances):
    L = [
        "# hcpack:hud codepoint table",
        "",
        "Generated by `src/tools/font.py`. Do not edit by hand.",
        "",
        f"All glyphs are 16x16, `height` {HEIGHT}, `ascent` {ASCENT}.",
        "A bitmap glyph advances **17 px** (width + 1), so `U+E106` (-17) backs up",
        "exactly one glyph and is what you use to overlay two icons.",
        "",
        "## Boss heads",
        "",
        "| Codepoint | Glyph |", "|---|---|",
    ]
    for name, cp in glyphs:
        if cp < 0xE100:
            L.append(f"| `U+{cp:04X}` | {name} |")

    L += ["", "## Armor", "",
          "`codepoint = 0xE200 + material_index * 4 + slot_index`", "",
          "material_index: " + ", ".join(f"{i} {m}" for i, m in enumerate(MATERIALS)),
          "", "slot_index: " + ", ".join(f"{i} {s}" for i, s in enumerate(SLOTS)),
          "", "Turtle is helmet-only - `U+E21D`..`U+E21F` are unassigned and render",
          "as a missing glyph. `empty` is the vanilla empty-slot outline, for a slot",
          "with nothing in it.", "",
          "| Codepoint | Glyph |", "|---|---|"]
    for name, cp in glyphs:
        if ARMOR_BASE <= cp < BAR_BASE:
            L.append(f"| `U+{cp:04X}` | {name} |")

    L += ["", "## Durability bars", "",
          f"`codepoint = 0x{BAR_BASE:04X} + filled`, where",
          "`filled = round(13 * remaining_durability / max_durability)`, 0..13.",
          "",
          "Each glyph is a full 16x16 transparent canvas with vanilla's item",
          "durability bar drawn into it: black trough plus the fill in vanilla's",
          "own colour ramp (green at full, through yellow, to red at empty).",
          "The colour is baked per step - do not tint it at runtime, component",
          "colour multiplies the texture.",
          "",
          "| Codepoint | Filled px |", "|---|---|"]
    for n in range(BAR_STEPS):
        L.append(f"| `U+{BAR_BASE + n:04X}` | {n} |")

    L += ["", "## Space", "",
          "| Codepoint | Advance |", "|---|---|"]
    for ch, adv in sorted(advances.items(), key=lambda kv: ord(kv[0])):
        L.append(f"| `U+{ord(ch):04X}` | {adv:+d} |")

    L += ["", "## Composing an armor slot with its durability bar", "",
          "Draw the armor glyph, back up one glyph with `U+E106` (-17), then draw",
          "the bar glyph. The bar sits in the lower rows of its own canvas, so it",
          "lands under the armor art without overlapping it.", "",
          "```",
          "U+E205  U+E106  U+E238      diamond chestplate, 8/13 durability",
          "```", ""]
    return "\n".join(L)


if __name__ == "__main__":
    build()
