#!/usr/bin/env python3
"""Generates pack/assets/hcpack/font/hud.json and CODEPOINTS.md."""
import json
import pathlib

# The two tuning knobs. Raising ASCENT moves the glyph up. ASCENT <= HEIGHT.
HEIGHT = 16
ASCENT = -46

# Boss glyphs carry the new 32px art inside the 18x18 inventory slot scaled 2x,
# so their canvas is 36x36. The ascent shifts by half the height difference so
# the art's vertical centre lands where the old 16px heads were.
BOSS_HEIGHT = 36
BOSS_ROW_GAP = 2

# A glyph's bottom sits at (height - ascent) below the text baseline, so matching the armor icons'
# bottom edge means solving BOSS_HEIGHT - A = HEIGHT - ASCENT for the LOWER row. The upper row is
# then one glyph plus the row gap higher. Deriving both from the armor line keeps the block pinned
# to the hotbar when ASCENT is retuned, instead of drifting off the bottom of the screen.
BOSS_ROW2_ASCENT = BOSS_HEIGHT - (HEIGHT - ASCENT)
BOSS_ASCENT = BOSS_ROW2_ASCENT + BOSS_HEIGHT + BOSS_ROW_GAP

# A second row cannot be produced by moving the pen - vertical position lives in
# the provider's ascent - so every boss head is registered twice, the lower copy
# at codepoint + 0x10 exactly one glyph height down. GlyphHud.bossBlock() draws
# row 2 by backing up and emitting the shifted codepoints; this is what makes a
# 2x2 cluster possible with boss-columns: 2.
BOSS_ROW_DELTA = 0x10

BOSSES = [
    ("dragon_grey", 0xE000), ("dragon", 0xE001),
    ("wither_grey", 0xE002), ("wither", 0xE003),
    ("warden_grey", 0xE004), ("warden", 0xE005),
    ("elder_grey",  0xE006), ("elder",  0xE007),
]

# Space advances. U+E100+i is negative, U+E110+i is the same value positive.
WIDTHS = [1, 2, 3, 4, 8, 16, 17, 32, 64]

# Armor block: U+E200 + material*4 + slot. Contiguous through U+E223.
ARMOR_BASE = 0xE200
MATERIALS = ["netherite", "diamond", "iron", "golden",
             "chainmail", "copper", "leather", "turtle", "empty"]
SLOTS = ["helmet", "chestplate", "leggings", "boots"]
# turtle is helmet-only; its other three codepoints stay unassigned.
MISSING = {("turtle", "chestplate"), ("turtle", "leggings"), ("turtle", "boots")}

# Durability block: U+E230 + filled, filled in 0..13.
BAR_BASE = 0xE230
BAR_STEPS = 14


def armor_cp(material, slot):
    return ARMOR_BASE + MATERIALS.index(material) * 4 + SLOTS.index(slot)


def build():
    advances = {}
    for i, w in enumerate(WIDTHS):
        advances[chr(0xE100 + i)] = -w
        advances[chr(0xE110 + i)] = w

    glyphs = list(BOSSES)
    for m in MATERIALS:
        for s in SLOTS:
            if (m, s) in MISSING:
                continue
            name = f"armor_{m}_{s}"
            glyphs.append((name, armor_cp(m, s)))
    glyphs += [(f"bar_{n}", BAR_BASE + n) for n in range(BAR_STEPS)]

    boss_names = {name for name, _ in BOSSES}
    providers = [{"type": "space", "advances": advances}]
    providers += [
        {"type": "bitmap", "file": f"hcpack:hud/{name}.png",
         "height": BOSS_HEIGHT if name in boss_names else HEIGHT,
         "ascent": BOSS_ASCENT if name in boss_names else ASCENT,
         "chars": [chr(cp)]}
        for name, cp in glyphs
    ]
    providers += [
        {"type": "bitmap", "file": f"hcpack:hud/{name}.png",
         "height": BOSS_HEIGHT, "ascent": BOSS_ROW2_ASCENT,
         "chars": [chr(cp + BOSS_ROW_DELTA)]}
        for name, cp in BOSSES
    ]

    root = pathlib.Path(__file__).parents[2]
    out = root / "pack/assets/hcpack/font/hud.json"
    out.write_text(json.dumps({"providers": providers}, indent=2, ensure_ascii=True) + "\n")
    (root / "CODEPOINTS.md").write_text(codepoints_md(glyphs, advances))
    print(f"{out}: height={HEIGHT} ascent={ASCENT}, "
          f"{len(providers) - 1} glyphs ({len(BOSSES)} boss heads registered twice)")
    return glyphs


def codepoints_md(glyphs, advances):
    L = [
        "# hcpack:hud codepoint table",
        "",
        "Generated by `src/tools/font.py`. Do not edit by hand.",
        "",
        f"Armor and bar glyphs are 16x16, `height` {HEIGHT}, `ascent` {ASCENT},",
        "and advance **17 px** (width + 1) - `U+E106` (-17) backs up exactly one",
        "of them, which is how a durability bar is slid under an armor icon.",
        "",
        f"Boss glyphs are 36x36 (32px art inside the vanilla inventory slot),",
        f"`height` {BOSS_HEIGHT}, `ascent` {BOSS_ASCENT}, and advance **37 px**.",
        "Four in a row is 148 px, which overruns the 115 px available per side -",
        "use two columns.",
        "",
        f"Every boss head is registered a second time at `codepoint + 0x{BOSS_ROW_DELTA:02X}`",
        f"(`U+E010`..`U+E017`) with `ascent` {BOSS_ROW2_ASCENT}, one glyph height lower.",
        "That second copy is the bottom row of a 2x2 cluster; GlyphHud draws it by",
        "backing the pen up a row and emitting the shifted codepoints.",
        "",
        "## Boss heads",
        "",
        "| Codepoint | Glyph |", "|---|---|",
    ]
    for name, cp in glyphs:
        if cp < 0xE100:
            L.append(f"| `U+{cp:04X}` | {name} |")
    for name, cp in BOSSES:
        L.append(f"| `U+{cp + BOSS_ROW_DELTA:04X}` | {name} (bottom row) |")

    L += ["", "## Armor", "",
          "`codepoint = 0xE200 + material_index * 4 + slot_index`", "",
          "material_index: " + ", ".join(f"{i} {m}" for i, m in enumerate(MATERIALS)),
          "", "slot_index: " + ", ".join(f"{i} {s}" for i, s in enumerate(SLOTS)),
          "", "Turtle is helmet-only - `U+E21D`..`U+E21F` are unassigned and render",
          "as a missing glyph. `empty` is the vanilla empty-slot outline, for a slot",
          "with nothing in it.", "",
          "| Codepoint | Glyph |", "|---|---|"]
    for name, cp in glyphs:
        if ARMOR_BASE <= cp < BAR_BASE:
            L.append(f"| `U+{cp:04X}` | {name} |")

    L += ["", "## Durability bars", "",
          f"`codepoint = 0x{BAR_BASE:04X} + filled`, where",
          "`filled = round(13 * remaining_durability / max_durability)`, 0..13.",
          "",
          "Each glyph is a full 16x16 transparent canvas with vanilla's item",
          "durability bar drawn into it: black trough plus the fill in vanilla's",
          "own colour ramp (green at full, through yellow, to red at empty).",
          "The colour is baked per step - do not tint it at runtime, component",
          "colour multiplies the texture.",
          "",
          "| Codepoint | Filled px |", "|---|---|"]
    for n in range(BAR_STEPS):
        L.append(f"| `U+{BAR_BASE + n:04X}` | {n} |")

    L += ["", "## Space", "",
          "| Codepoint | Advance |", "|---|---|"]
    for ch, adv in sorted(advances.items(), key=lambda kv: ord(kv[0])):
        L.append(f"| `U+{ord(ch):04X}` | {adv:+d} |")

    L += ["", "## Composing an armor slot with its durability bar", "",
          "Draw the armor glyph, back up one glyph with `U+E106` (-17), then draw",
          "the bar glyph. The bar sits in the lower rows of its own canvas, so it",
          "lands under the armor art without overlapping it.", "",
          "```",
          "U+E205  U+E106  U+E238      diamond chestplate, 8/13 durability",
          "```", ""]
    return "\n".join(L)


if __name__ == "__main__":
    build()
